# This file is provided to streamline Conda virtual environment generation
# Using conda (instead of poetry) is necessary to install Pygmo and access IPOPT/SNOPT
name: jaxprop_env2
channels:
 - conda-forge
dependencies:
  - python=3.13
  - pip
  - poetry
  